language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t elseifj/docker-react -f Dcokerfile.dev .

script:
  - docker run -e CI=true elseifj/docker-react npm run test